[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && next build"

[deploy]
startCommand = "DATABASE_URL=$DATABASE_URL_PUBLIC npx prisma migrate deploy && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/auth/session"
healthcheckTimeout = 100

[environment]
NODE_ENV = "production"