[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npx prisma migrate deploy && next build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/auth/session"
healthcheckTimeout = 100

[environment]
NODE_ENV = "production"