[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && next build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"