-- CreateEnum
CREATE TYPE "EVENT_TYPE" AS ENUM ('APPOINTMENT', 'BOOTCAMP', 'WORKOUT');

-- AlterTable
ALTER TABLE "Appointment" ADD COLUMN     "type" "EVENT_TYPE" NOT NULL DEFAULT 'APPOINTMENT';

-- AlterTable
ALTER TABLE "Bootcamp" ADD COLUMN     "type" "EVENT_TYPE" NOT NULL DEFAULT 'BOOTCAMP';

-- AlterTable
ALTER TABLE "Workout" ADD COLUMN     "type" "EVENT_TYPE" NOT NULL DEFAULT 'WORKOUT';
